name: Add Tag

run-name: Add Tag:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
 push:
   branches:
     - main

jobs:
  add-tag:
    runs-on: ubuntu-latest

    container:
      image: ros:humble-ros-base

    permissions:
      contents: write

    steps:
      - name: Resist repository name
        id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      
      - id: tag_name
        run: echo name=$(xmllint --xpath /package/version package.xml | sed 's/^.*<version.*>\(.*\)<\/version>.*$/v\1/') >> $GITHUB_OUTPUT

      - name: Add safe directory
        run: git config --global --add safe.directory /__w/${{ steps.repository.outputs.name }}/${{ steps.repository.outputs.name }}
      
      - name: Add tag
        run: git tag ${{ steps.tag_name.outputs.name }}
      
      - name: Push
        run: git push origin ${{ steps.tag_name.outputs.name }}