name: Test

run-name: Test:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    container:
      image: ros:humble-ros-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/traps_tools_ros

      - name: Install package by apt
        run: apt-get update && apt-get install -y

      - name: Install package by rosdep
        run: rosdep update && rosdep install -iy --from-paths .
      
      - name: Build
        run: . /opt/ros/humble/setup.sh && colcon build
      
      - name: Test
        run: . /opt/ros/humble/setup.sh && colcon test && colcon test-result --verbose