name: Version Check

run-name: Version Check:${{ github.event.pull_request.title  }}

on:
  pull_request:

jobs:
  version-chack:
    runs-on: ubuntu-22.04

    steps:
      - name: Skip check
        if: ${{ github.base_ref == 'main' }}
        run: echo "Skip because it is not a merge to Main Brunch" && exit 0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
      
      - id: latest_id
        run: git describe --tags --abbrev=0 >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
      
      - id: current_id
        run: xmllint --xpath /package/version package.xml | sed 's/^.*<version.*>\(.*\)<\/version>.*$/v\1/' >> $GITHUB_OUTPUT
      
      - id: check_version
        run: echo ${{ steps.latest_id.outputs.name != steps.current_id.outputs.name }} >> $GITHUB_OUTPUT

      - name: Faile
        if: ${{ !steps.check_version.outputs.name }}
        run: echo You need to change the version before merging to main && exit 1

      - name: Success
        if: ${{ steps.check_version.outputs.name }}
        run: echo Success to check version